# settings.py

PIXEL_SCALE = 3
ORIGINAL_BG_LAYER_HEIGHT_PX = 240
SCALED_BG_LAYER_HEIGHT_PX = ORIGINAL_BG_LAYER_HEIGHT_PX * PIXEL_SCALE

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 600

PLAYER_SPEED = 300
CAMERA_SPEED = 0.1

FADE_IN_SPEED = 0.02
FADE_OUT_SPEED = 0.01
DIALOGUE_DISPLAY_TIME = 180  # frames
